<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="showcameras.xsl" ?>
<!--
    License: CC-BY-SA 3.0

    This work is licensed under a 
    Creative Commons Attribution-ShareAlike 3.0 Unported License. 

    See more at:
    http://creativecommons.org/licenses/by-sa/3.0/
-->

<!DOCTYPE Cameras [
<!ELEMENT BlackAreas ( Vertical*, Horizontal* ) >

<!ELEMENT Camera ( CFA?, Crop, Sensor+, BlackAreas?, Aliases?, Hints? ) >
<!ATTLIST Camera make CDATA #REQUIRED >
<!ATTLIST Camera model CDATA #REQUIRED >
<!ATTLIST Camera supported CDATA #IMPLIED >
<!ATTLIST Camera mode CDATA #IMPLIED >
<!ATTLIST Camera decoder_version CDATA #IMPLIED >

<!ELEMENT Cameras ( Camera+ ) >
<!ATTLIST Cameras version CDATA #IMPLIED >

<!ELEMENT CFA ( Color+ ) >
<!ATTLIST CFA height NMTOKEN #REQUIRED >
<!ATTLIST CFA width NMTOKEN #REQUIRED >

<!ELEMENT Color ( #PCDATA ) >
<!ATTLIST Color x NMTOKEN #REQUIRED >
<!ATTLIST Color y NMTOKEN #REQUIRED >

<!ELEMENT Crop EMPTY >
<!ATTLIST Crop height NMTOKEN #REQUIRED >
<!ATTLIST Crop width NMTOKEN #REQUIRED >
<!ATTLIST Crop x NMTOKEN #REQUIRED >
<!ATTLIST Crop y NMTOKEN #REQUIRED >

<!ELEMENT Horizontal EMPTY >
<!ATTLIST Horizontal height NMTOKEN #REQUIRED >
<!ATTLIST Horizontal y NMTOKEN #REQUIRED >

<!ELEMENT Sensor EMPTY >
<!ATTLIST Sensor white NMTOKEN #REQUIRED >
<!ATTLIST Sensor black NMTOKEN #REQUIRED >
<!ATTLIST Sensor iso_min NMTOKEN #IMPLIED >
<!ATTLIST Sensor iso_max NMTOKEN #IMPLIED >

<!ELEMENT Vertical EMPTY >
<!ATTLIST Vertical width NMTOKEN #REQUIRED >
<!ATTLIST Vertical x NMTOKEN #REQUIRED >

<!ELEMENT Hints ( Hint+ ) >
<!ELEMENT Hint EMPTY >
<!ATTLIST Hint name CDATA #REQUIRED >
<!ATTLIST Hint value CDATA #REQUIRED >

<!ELEMENT Aliases ( Alias+ ) >
<!ELEMENT Alias (#PCDATA) >
]>

<Cameras>
  <Camera make="Canon" model="Canon EOS 20D">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="74" y="12" width="3522" height="2348"/>
    <Sensor black="126" white="4095"/>
	<BlackAreas>
		<Vertical x="0" width="72"/>
		<Horizontal y="2" height="8"/>
	</BlackAreas>
  </Camera>
  <Camera make="Canon" model="Canon EOS 30D">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="74" y="12" width="3522" height="2348"/>
    <Sensor black="127" white="3398"/>
	<BlackAreas>
		<Vertical x="0" width="72"/>
		<Horizontal y="2" height="8"/>
	</BlackAreas>
  </Camera>
  <Camera make="Canon" model="Canon EOS 350D DIGITAL">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="42" y="14" width="3474" height="2314"/>
    <Sensor black="255" white="4095"/>
	<BlackAreas>
		<Vertical x="0" width="40"/>
		<Horizontal y="0" height="12"/>
	</BlackAreas>
    <Aliases>
		<Alias>Canon EOS DIGITAL REBEL XT</Alias>
		<Alias>Canon EOS Kiss Digital N</Alias>
		<Alias>Canon EOS 350D</Alias>
	</Aliases>
  </Camera>
  <Camera make="Canon" model="Canon EOS 40D">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="30" y="18" width="3908" height="2602"/>
    <Sensor black="1021" white="13600"/>
	<BlackAreas>
		<Vertical x="0" width="28"/>
		<Horizontal y="4" height="12"/>
	</BlackAreas>
  </Camera>
  <Camera make="Canon" model="Canon EOS 40D" mode="sRaw2">
    <Crop x="0" y="0" width="1944" height="1296"/>
    <Sensor black="0" white="16383"/>
  </Camera>
  <Camera make="Canon" model="Canon EOS 450D">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="22" y="18" width="4290" height="2856"/>
    <Sensor black="1020" white="14500"/>
    <Aliases>
		<Alias>Canon EOS DIGITAL REBEL XSi</Alias>
		<Alias>Canon EOS Kiss Digital X2</Alias>
	</Aliases>
  </Camera>
  <Camera make="Canon" model="Canon EOS 50D">
    <CFA width="2" height="2">
      <Color x="0" y="0">GREEN</Color>
      <Color x="1" y="0">BLUE</Color>
      <Color x="0" y="1">RED</Color>
      <Color x="1" y="1">GREEN</Color>
    </CFA>
    <Crop x="64" y="52" width="4752" height="3158"/>
    <Sensor black="1020" white="16383"/>
	<BlackAreas>
		<Vertical x="0" width="60"/>
		<Horizontal y="2" height="46"/>
	</BlackAreas>
  </Camera>
  <Camera make="Canon" model="Canon EOS 50D" mode="sRaw1">
    <Crop x="0" y="0" width="3272" height="2178"/>
    <Sensor black="0" white="16383"/>
  </Camera>
  <Camera make="Canon" model="Canon EOS 50D" mode="sRaw2">
    <Crop x="0" y="0" width="2376" height="1584"/>
    <Sensor black="0" white="16383"/>
  </Camera>
  <Camera make="Canon" model="Canon EOS 60D">
    <CFA width="2" height="2">
      <Color x="0" y="0">GREEN</Color>
      <Color x="1" y="0">BLUE</Color>
      <Color x="0" y="1">RED</Color>
      <Color x="1" y="1">GREEN</Color>
    </CFA>
    <Crop x="146" y="54" width="0" height="0"/>
    <Sensor black="2026" white="14200"/>
	<BlackAreas>
		<Vertical x="0" width="140"/>
		<Horizontal y="4" height="46"/>
	</BlackAreas>
  </Camera>
  <Camera make="Canon" model="Canon EOS 60D" mode="sRaw1">
    <Crop x="0" y="0" width="0" height="0"/>
    <Sensor black="0" white="16383"/>
  </Camera>  
  <Camera make="Canon" model="Canon EOS 60D" mode="sRaw2">
    <Crop x="0" y="0" width="0" height="0"/>
    <Sensor black="0" white="16383"/>
  </Camera>  
  <Camera make="Canon" model="Canon EOS 500D">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="62" y="30" width="4722" height="3142"/>
    <Sensor black="1020" white="16000"/>
	<BlackAreas>
		<Vertical x="0" width="56"/>
		<Horizontal y="2" height="22"/>
	</BlackAreas>
    <Aliases>
		<Alias>Canon EOS REBEL T1i</Alias>
		<Alias>Canon EOS Kiss X3</Alias>
	</Aliases>
  </Camera>
  <Camera make="Canon" model="Canon EOS 550D">
    <CFA width="2" height="2">
      <Color x="1" y="0">BLUE</Color>
      <Color x="0" y="0">GREEN</Color>
      <Color x="1" y="1">GREEN</Color>
      <Color x="0" y="1">RED</Color>
    </CFA>
    <Crop x="148" y="54" width="0" height="0"/>
    <Sensor black="2048" white="15831"/>
	<BlackAreas>
		<Vertical x="0" width="140"/>
		<Horizontal y="4" height="44"/>
	</BlackAreas>
    <Aliases>
		<Alias>Canon EOS REBEL T2i</Alias>
		<Alias>Canon EOS Kiss X4</Alias>
	</Aliases>
  </Camera>
  <Camera make="Canon" model="Canon EOS 600D">
    <CFA width="2" height="2">
      <Color x="0" y="0">GREEN</Color>
      <Color x="1" y="0">BLUE</Color>
      <Color x="0" y="1">RED</Color>
      <Color x="1" y="1">GREEN</Color>
    </CFA>
    <Crop x="146" y="54" width="0" height="0"/>
    <Sensor black="2026" white="13584" iso_min="0" iso_max = "199"/>
    <Sensor black="2026" white="15304"/>
	<BlackAreas>
		<Vertical x="0" width="140"/>
		<Horizontal y="4" height="44"/>
	</BlackAreas>
    <Aliases>
		<Alias>Canon EOS REBEL T3i</Alias>
		<Alias>Canon EOS Kiss X5</Alias>
	</Aliases>
  </Camera>
  <Camera make="Canon" model="Canon EOS 5D">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="90" y="34" width="4386" height="2920"/>
    <Sensor black="127" white="3692"/>
	<BlackAreas>
		<Vertical x="0" width="88"/>
		<Horizontal y="2" height="30"/>
	</BlackAreas>
  </Camera>
  <Camera make="Canon" model="Canon EOS 5D Mark II">
    <CFA width="2" height="2">
      <Color x="0" y="0">GREEN</Color>
      <Color x="1" y="0">BLUE</Color>
      <Color x="0" y="1">RED</Color>
      <Color x="1" y="1">GREEN</Color>
    </CFA>
    <Crop x="158" y="51" width="5634" height="3753"/>
    <Sensor black="1024" white="15600"/>
	<BlackAreas>
		<Vertical x="0" width="156"/>
		<Horizontal y="2" height="48"/>
	</BlackAreas>
  </Camera>
  <Camera make="Canon" model="Canon EOS 5D Mark II" mode="sRaw1">
    <Crop x="0" y="0" width="3872" height="2574"/>
    <Sensor black="0" white="15600"/>
  </Camera>
  <Camera make="Canon" model="Canon EOS 5D Mark II" mode="sRaw2">
    <Crop x="0" y="0" width="2808" height="1872"/>
    <Sensor black="0" white="15600"/>
  </Camera>
  <Camera make="Canon" model="Canon EOS 5D Mark III">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="124" y="82" width="-2" height="0"/>
    <Sensor black="1024" white="16383"/>
  <BlackAreas>
    <Vertical x="0" width="120"/>
    <Horizontal y="2" height="78"/>
  </BlackAreas>
  </Camera>
  <!-- Unconfirmed: -->
  <Camera make="Canon" model="Canon EOS 5D Mark III" mode="sRaw1">
    <Crop x="0" y="0" width="0" height="0"/>
    <Sensor black="0" white="16383"/>
  </Camera>
  <!-- Unconfirmed: -->
  <Camera make="Canon" model="Canon EOS 5D Mark III" mode="sRaw2">
    <Crop x="0" y="0" width="0" height="0"/>
    <Sensor black="0" white="16383"/>
  </Camera>
  <Camera make="Canon" model="Canon EOS 7D">
    <CFA width="2" height="2">
      <Color x="0" y="0">GREEN</Color>
      <Color x="1" y="0">BLUE</Color>
      <Color x="0" y="1">RED</Color>
      <Color x="1" y="1">GREEN</Color>
    </CFA>
    <Crop x="158" y="52" width="5202" height="3464"/>
    <Sensor black="1025" white="8150" iso_min="12800" iso_max="12800"/>
    <Sensor black="2050" white="16300"/>
	<BlackAreas>
		<Vertical x="0" width="156"/>
		<Horizontal y="2" height="48"/>
	</BlackAreas>
  </Camera>
  <Camera make="Canon" model="Canon EOS 7D" mode="sRaw1">
    <Crop x="0" y="0" width="0" height="0"/>
    <Sensor black="0" white="16383"/>
  </Camera>  
  <Camera make="Canon" model="Canon EOS 7D" mode="sRaw2">
    <Crop x="0" y="0" width="0" height="0"/>
    <Sensor black="0" white="16383"/>
  </Camera>  
  <Camera make="Canon" model="Canon EOS 1000D">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="42" y="18" width="3906" height="2602"/>
    <Sensor black="255" white="3650" iso_min="0" iso_max="199"/>
    <Sensor black="255" white="4036"/>
	<BlackAreas>
		<Vertical x="0" width="41"/>
		<Horizontal y="2" height="14"/>
	</BlackAreas>
    <Aliases>
		<Alias>Canon EOS DIGITAL REBEL XS</Alias>
		<Alias>Canon EOS Kiss Digital F</Alias>
	</Aliases>
  </Camera>
  <Camera make="Canon" model="Canon EOS 1100D">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="64" y="20" width="0" height="0"/>
    <Sensor black="2036" white="15500"/>
	<BlackAreas>
		<Vertical x="0" width="58"/>
		<Horizontal y="4" height="12"/>
	</BlackAreas>
    <Aliases>
		<Alias>Canon EOS REBEL T3</Alias>
	</Aliases>
  </Camera>
  <Camera make="Canon" model="Canon EOS 400D DIGITAL">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="42" y="18" width="3906" height="2602"/>
    <Sensor black="255" white="3726"/>
	<BlackAreas>
		<Vertical x="0" width="40"/>
		<Horizontal y="4" height="12"/>
	</BlackAreas>
    <Aliases>
		<Alias>Canon EOS DIGITAL REBEL XTi</Alias>
		<Alias>Canon EOS Kiss Digital X</Alias>
	</Aliases>
  </Camera>
  <Camera make="Canon" model="Canon EOS-1D Mark II">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="74" y="12" width="3522" height="2348"/>
    <Sensor black="127" white="3700"/>
	<BlackAreas>
		<Vertical x="0" width="72"/>
		<Horizontal y="2" height="8"/>
	</BlackAreas>
  </Camera>
  <Camera make="Canon" model="Canon EOS-1D Mark II N">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="74" y="12" width="3522" height="2348"/>
    <Sensor black="127" white="3700"/>
	<BlackAreas>
		<Vertical x="0" width="72"/>
		<Horizontal y="2" height="8"/>
	</BlackAreas>
  </Camera>
  <Camera make="Canon" model="Canon EOS-1D Mark III">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="78" y="20" width="3906" height="2600"/>
    <Sensor black="1023" white="15100"/>
	<BlackAreas>
		<Vertical x="2" width="74"/>
		<Horizontal y="4" height="14"/>
	</BlackAreas>
  </Camera>
  <Camera make="Canon" model="Canon EOS-1D Mark III" mode="sRaw1">
    <Crop x="0" y="0" width="0" height="0"/>
    <Sensor black="0" white="16383"/>
  </Camera>
  <Camera make="Canon" model="Canon EOS-1D Mark III" mode="sRaw2">
    <Crop x="0" y="0" width="0" height="0"/>
    <Sensor black="0" white="16383"/>
  </Camera>
  <Camera make="Canon" model="Canon EOS-1D Mark IV">
    <CFA width="2" height="2">
      <Color x="0" y="0">GREEN</Color>
      <Color x="1" y="0">BLUE</Color>
      <Color x="0" y="1">RED</Color>
      <Color x="1" y="1">GREEN</Color>
    </CFA>
    <Crop x="144" y="46" width="-64" height="-2"/>
    <Sensor black="2000" white="15900"/>
	<BlackAreas>
		<Vertical x="0" width="140"/>
		<Horizontal y="26" height="16"/>
	</BlackAreas>
  </Camera>
  <Camera make="Canon" model="Canon EOS-1D Mark IV" mode="sRaw1">
    <Crop x="0" y="0" width="0" height="0"/>
    <Sensor black="0" white="16383"/>
  </Camera>
  <Camera make="Canon" model="Canon EOS-1D Mark IV" mode="sRaw2">
    <Crop x="0" y="0" width="0" height="0"/>
    <Sensor black="0" white="16383"/>
  </Camera>
  <Camera make="Canon" model="Canon EOS-1Ds Mark II">
    <CFA width="2" height="2">
      <Color x="0" y="0">GREEN</Color>
      <Color x="1" y="0">BLUE</Color>
      <Color x="0" y="1">RED</Color>
      <Color x="1" y="1">GREEN</Color>
    </CFA>
    <Crop x="98" y="13" width="5010" height="3336"/>
    <Sensor black="126" white="4060"/>
	<BlackAreas>
		<Vertical x="0" width="96"/>
		<Horizontal y="2" height="10"/>
	</BlackAreas>
  </Camera>
  <Camera make="Canon" model="Canon EOS-1Ds Mark III">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="62" y="20" width="5640" height="3752"/>
    <Sensor black="1021" white="15100"/>
	<BlackAreas>
		<Vertical x="0" width="60"/>
		<Horizontal y="4" height="14"/>
	</BlackAreas>
  </Camera>
  <Camera make="Canon" model="Canon EOS-1Ds Mark III" mode="sRaw1">
    <Crop x="0" y="0" width="0" height="0"/>
    <Sensor black="0" white="16383"/>
  </Camera>
  <Camera make="Canon" model="Canon EOS-1Ds Mark III" mode="sRaw2">
    <Crop x="0" y="0" width="0" height="0"/>
    <Sensor black="0" white="16383"/>
  </Camera>
  <Camera make="Canon" model="Canon PowerShot G1 X">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="82" y="52" width="-14" height="0"/>
    <Sensor black="0" white="16383"/>
	<BlackAreas>
		<Vertical x="0" width="68"/>
		<Horizontal y="0" height="46"/>
	</BlackAreas>
  </Camera>
  <Camera make="Canon" model="Canon PowerShot G12">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="54" y="14" width="-12" height="-18"/>
    <Sensor black="120" white="4095"/>
	<BlackAreas>
		<Vertical x="0" width="50"/>
		<Horizontal y="0" height="10"/>
	</BlackAreas>
  </Camera>
  <Camera make="Canon" model="Canon PowerShot G11">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="10" y="18" width="-56" height="-14"/>
    <Sensor black="120" white="4095"/>
	<BlackAreas>
		<Vertical x="0" width="10"/>
		<Horizontal y="0" height="14"/>
	</BlackAreas>
  </Camera>
  <Camera make="Canon" model="Canon PowerShot G10">
    <CFA width="2" height="2">
      <Color x="0" y="0">GREEN</Color>
      <Color x="1" y="0">BLUE</Color>
      <Color x="0" y="1">RED</Color>
      <Color x="1" y="1">GREEN</Color>
    </CFA>
    <Crop x="12" y="13" width="4432" height="3323"/>
    <Sensor black="128" white="4095"/>
	<BlackAreas>
		<Vertical x="0" width="10"/>
		<Horizontal y="0" height="8"/>
	</BlackAreas>
  </Camera>
  <Camera make="Canon" model="Canon PowerShot G9">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="48" y="12" width="4032" height="3024"/>
    <Sensor black="125" white="4095"/>
	<BlackAreas>
		<Vertical x="0" width="46"/>
		<Horizontal y="0" height="8"/>
	</BlackAreas>
  </Camera>
  <Camera make="Canon" model="Canon PowerShot SX1 IS">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="192" y="12" width="3958" height="2760"/>
    <Sensor black="125" white="4095"/>
	<BlackAreas>
		<Vertical x="0" width="188"/>
		<Horizontal y="0" height="10"/>
	</BlackAreas>
  </Camera>
  <Camera make="Canon" model="Canon PowerShot S90">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="10" y="18" width="-54" height="-10"/>
    <Sensor black="125" white="4095"/>
	<BlackAreas>
		<Vertical x="0" width="6"/>
		<Horizontal y="0" height="14"/>
	</BlackAreas>
  </Camera>
  <Camera make="Canon" model="Canon PowerShot S95">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color><Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color><Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="66" y="24" width="-20" height="-24"/>
    <Sensor black="125" white="4095"/>
	<BlackAreas>
		<Vertical x="0" width="50"/>
		<Vertical x="3738" width="6"/>
		<Horizontal y="0" height="10"/>
		<Horizontal y="2774" height="10"/>
	</BlackAreas>
  </Camera>
  <Camera make="Canon" model="Canon PowerShot S100">
    <CFA width="2" height="2">
      <Color x="0" y="0">GREEN</Color><Color x="1" y="0">BLUE</Color>
      <Color x="0" y="1">RED</Color><Color x="1" y="1">GREEN</Color>
    </CFA>
    <Crop x="104" y="12" width="-10" height="-66"/>
    <Sensor black="125" white="4095"/>
	<BlackAreas>
		<Vertical x="0" width="100"/>
		<Horizontal y="0" height="10"/>
		<Horizontal y="3062" height="60"/>
	</BlackAreas>
  </Camera>	
  <Camera make="NIKON CORPORATION" model="NIKON D100">
    <CFA width="2" height="2">
      <Color x="0" y="0">GREEN</Color>
      <Color x="1" y="0">RED</Color>
      <Color x="0" y="1">BLUE</Color>
      <Color x="1" y="1">GREEN</Color>
    </CFA>
    <Crop x="2" y="0" width="3030" height="2024"/>
    <Sensor black="0" white="4095"/>
  </Camera>
  <Camera make="NIKON CORPORATION" model="NIKON D1">
    <CFA width="2" height="2">
      <Color x="0" y="0">BLUE</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">RED</Color>
    </CFA>
    <Crop x="0" y="0" width="2000" height="1312"/>
    <Sensor black="0" white="4095"/>
  </Camera>
  <Camera make="NIKON CORPORATION" model="NIKON D1H">
    <CFA width="2" height="2">
      <Color x="0" y="0">BLUE</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">RED</Color>
    </CFA>
    <Crop x="0" y="0" width="2012" height="1324"/>
    <Sensor black="0" white="4095"/>
  </Camera>
  <Camera make="NIKON CORPORATION" model="NIKON D1X" supported="no">
    <CFA width="2" height="2">
      <Color x="0" y="0">BLUE</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">RED</Color>
    </CFA>
    <Crop x="0" y="0" width="4024" height="1324"/>
    <Sensor black="0" white="4095"/>
  </Camera>
  <Camera make="NIKON CORPORATION" model="NIKON D200">
    <CFA width="2" height="2">
      <Color x="0" y="0">GREEN</Color>
      <Color x="1" y="0">RED</Color>
      <Color x="0" y="1">BLUE</Color>
      <Color x="1" y="1">GREEN</Color>
    </CFA>
    <Crop x="2" y="0" width="3898" height="2616"/>
    <Sensor black="0" white="3880"/>
  </Camera>
  <Camera make="NIKON CORPORATION" model="NIKON D2H">
    <CFA width="2" height="2">
      <Color x="0" y="0">GREEN</Color>
      <Color x="1" y="0">BLUE</Color>
      <Color x="0" y="1">RED</Color>
      <Color x="1" y="1">GREEN</Color>
    </CFA>
    <Crop x="6" y="0" width="-8" height="1648"/>
    <Sensor black="0" white="3880"/>
  </Camera>
  <Camera make="NIKON CORPORATION" model="NIKON D2Hs">
    <CFA width="2" height="2">
      <Color x="0" y="0">GREEN</Color>
     <Color x="1" y="0">BLUE</Color>
      <Color x="0" y="1">RED</Color>
      <Color x="1" y="1">GREEN</Color>
    </CFA>
    <Crop x="6" y="0" width="-8" height="1648"/>
    <Sensor black="0" white="3880"/>
  </Camera>
  <Camera make="NIKON CORPORATION" model="NIKON D2X">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="0" y="0" width="-32" height="-8"/>
    <Sensor black="0" white="3880"/>
  </Camera>
  <Camera make="NIKON CORPORATION" model="NIKON D3">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="2" y="0" width="4282" height="2844"/>
    <Sensor black="0" white="16384"/>
  </Camera>
  <Camera make="NIKON CORPORATION" model="NIKON D3S">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="0" y="0" width="0" height="0"/>
    <Sensor black="0" white="16384"/>
  </Camera>
  <Camera make="NIKON CORPORATION" model="NIKON D3X">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="0" y="0" width="6080" height="4044"/>
    <Sensor black="0" white="16384"/>
  </Camera>
  <Camera make="NIKON CORPORATION" model="NIKON D300">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="0" y="0" width="4320" height="2868"/>
    <Sensor black="0" white="15236"/>
  </Camera>
  <Camera make="NIKON CORPORATION" model="NIKON D300S">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="0" y="0" width="4320" height="2868"/>
    <Sensor black="0" white="15236"/>
  </Camera>
  <Camera make="NIKON CORPORATION" model="NIKON D3000">
    <CFA width="2" height="2">
      <Color x="0" y="0">GREEN</Color>
      <Color x="1" y="0">BLUE</Color>
      <Color x="0" y="1">RED</Color>
      <Color x="1" y="1">GREEN</Color>
    </CFA>
    <Crop x="0" y="0" width="3898" height="2610"/>
    <Sensor black="0" white="16383"/>
  </Camera>
  <Camera make="NIKON CORPORATION" model="NIKON D4">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="2" y="0" width="-50" height="0"/>
    <Sensor black="0" white="16383"/>
		<BlackAreas>
			<Vertical x="4984" width="8"/>
		</BlackAreas>
  </Camera>
  <Camera make="NIKON CORPORATION" model="NIKON D5100"  decoder_version="2">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="0" y="0" width="-46" height="0"/>
    <Sensor black="0" white="65536"/>
  </Camera>
  <Camera make="NIKON CORPORATION" model="NIKON D3100"  decoder_version="2">
    <CFA width="2" height="2">
      <Color x="0" y="0">GREEN</Color>
      <Color x="1" y="0">BLUE</Color>
      <Color x="0" y="1">RED</Color>
      <Color x="1" y="1">GREEN</Color>
    </CFA>
    <Crop x="8" y="2" width="-24" height="-2"/>
    <Sensor black="0" white="16383"/>
  </Camera>
  <Camera make="NIKON CORPORATION" model="NIKON D40">
    <CFA width="2" height="2">
      <Color x="0" y="0">BLUE</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">RED</Color>
    </CFA>
    <Crop x="0" y="0" width="3038" height="2014"/>
    <Sensor black="0" white="3880"/>
  </Camera>
  <Camera make="NIKON CORPORATION" model="NIKON D40X">
    <CFA width="2" height="2">
      <Color x="0" y="0">GREEN</Color>
      <Color x="1" y="0">BLUE</Color>
      <Color x="0" y="1">RED</Color>
      <Color x="1" y="1">GREEN</Color>
    </CFA>
    <Crop x="4" y="0" width="3896" height="2613"/>
    <Sensor black="0" white="3880"/>
  </Camera>
  <Camera make="NIKON CORPORATION" model="NIKON D50">
    <CFA width="2" height="2">
      <Color x="0" y="0">BLUE</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">RED</Color>
    </CFA>
    <Crop x="0" y="0" width="-2" height="-2"/>
    <Sensor black="0" white="3880"/>
  </Camera>
  <Camera make="NIKON CORPORATION" model="NIKON D5000">
    <CFA width="2" height="2">
      <Color x="0" y="0">GREEN</Color>
      <Color x="1" y="0">BLUE</Color>
      <Color x="0" y="1">RED</Color>
      <Color x="1" y="1">GREEN</Color>
    </CFA>
    <Crop x="0" y="0" width="4310" height="2868"/>
    <Sensor black="0" white="4096"/>
  </Camera>
  <Camera make="NIKON CORPORATION" model="NIKON D60">
    <CFA width="2" height="2">
      <Color x="0" y="0">GREEN</Color>
      <Color x="1" y="0">BLUE</Color>
      <Color x="0" y="1">RED</Color>
      <Color x="1" y="1">GREEN</Color>
    </CFA>
    <Crop x="0" y="0" width="3900" height="2613"/>
    <Sensor black="0" white="3880"/>
  </Camera>
  <Camera make="NIKON CORPORATION" model="NIKON D70">
    <CFA width="2" height="2">
      <Color x="0" y="0">BLUE</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">RED</Color>
    </CFA>
    <Crop x="0" y="0" width="3038" height="2014"/>
    <Sensor black="0" white="4095"/>
  </Camera>
  <Camera make="NIKON CORPORATION" model="NIKON D700">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="2" y="0" width="4282" height="2844"/>
    <Sensor black="0" white="3972"/>
  </Camera>
  <Camera make="NIKON CORPORATION" model="NIKON D7000">
    <CFA width="2" height="2">
      <Color x="0" y="0">RED</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">BLUE</Color>
    </CFA>
    <Crop x="0" y="0" width="-46" height="-2"/>
    <Sensor black="0" white="4095"/>
  </Camera>
  <Camera make="NIKON CORPORATION" model="NIKON D70s">
    <CFA width="2" height="2">
      <Color x="0" y="0">BLUE</Color>
      <Color x="1" y="0">GREEN</Color>
      <Color x="0" y="1">GREEN</Color>
      <Color x="1" y="1">RED</Color>
    </CFA>
    <Crop x="0" y="0" width="3040" height="2014"/>
    <Sensor black="0" white="4095"/>
  </Camera>
  <Camera make="NIKON CORPORATION" model="NIKON D80">
    <CFA width="2" height="2">
      <Color x="0" y="0">GREEN</Color>